# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_mvvm_swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift',    '4.3.1'
    pod 'RxCocoa',    '4.3.1'

  target 'ios_mvvm_swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_mvvm_swiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
